services:
  api:
    container_name: rails-s-api
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
      args:
        - RAILS_ENV=${RAILS_ENV}
        - BUNDLER_VERSION=${BUNDLER_VERSION}
        - LANG=${LANG}
        - TZ=${TZ}
        - PORT=${PORT}
    volumes:
      - .:/api
    ports:
      - 3010:${PORT}
    env_file:
      - ./.env
    depends_on:
        - db
    command: bundle exec puma -C "config/puma.rb"
  # DBに関する設定
  db:
    container_name: rails-s-db
    image: mysql:8.0.36
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./tmp/db:/var/lib/mysql